:commit_author_email:
  :enabled: true
:commit_author_name_capitalization:
  :enabled: true
:commit_author_name_parts:
  :enabled: true
  :minimum: 2
:commit_body_bullet:
  :enabled: true
  :blacklist:
    - "*"
    - "•"
:commit_body_leading_space:
  :enabled: true
:commit_body_line_length:
  :enabled: true
  :length: 72
:commit_body_phrase:
  :enabled: true
  :blacklist:
    - obviously
    - basically
    - simply
    - of course
    - just
    - everyone knows
    - however
    - easy
:commit_subject_length:
  :enabled: true
  :length: 72
:commit_subject_prefix:
  :enabled: true
  :whitelist:
    - Fixed
    - Added
    - Updated
    - Removed
    - Refactored
    - Renamed
    - Moved
:commit_subject_suffix:
  :enabled: true
  :whitelist:
    - "."
